name: Build Kivy App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip openjdk-17-jdk
          pip install --upgrade pip
          pip install buildozer cython virtualenv

      - name: Set up Buildozer
        run: |
          buildozer init
          cp buildozer.spec buildozer.spec.bak
          mv buildozer.spec.bak buildozer.spec

      - name: Accept Android SDK Licenses
        run: yes | sdkmanager --licenses

      - name: Build APK
        run: buildozer -v android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: PharmacyApp-APK
          path: bin/*.apk
          
