name: Build Kivy APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip openjdk-17-jdk unzip
        pip install --upgrade pip
        pip install buildozer cython virtualenv kivy

    - name: Initialize Buildozer
      run: |
        buildozer init

    - name: Configure Buildozer Spec
      run: |
        sed -i 's/^# requirements = python3,kivy$/requirements = python3,kivy,pytz,sqlite3/g' buildozer.spec
        sed -i 's/^# android.arch = arm64-v8a$/android.arch = arm64-v8a/g' buildozer.spec

    - name: Build APK
      run: |
        buildozer -v android debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Kivy-Pharmacy-App
        path: bin/*.apk
